In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('stocks.csv')

In [3]:
dataset

Ticker        Date        Open        High         Low       Close  \
0     AAPL  2023-02-07  150.639999  155.229996  150.639999  154.649994   
1     AAPL  2023-02-08  153.880005  154.580002  151.169998  151.919998   
2     AAPL  2023-02-09  153.779999  154.330002  150.419998  150.869995   
3     AAPL  2023-02-10  149.460007  151.339996  149.220001  151.009995   
4     AAPL  2023-02-13  150.949997  154.259995  150.919998  153.850006   
..     ...         ...         ...         ...         ...         ...   
243   GOOG  2023-05-01  107.720001  108.680000  107.500000  107.709999   
244   GOOG  2023-05-02  107.660004  107.730003  104.500000  105.980003   
245   GOOG  2023-05-03  106.220001  108.129997  105.620003  106.120003   
246   GOOG  2023-05-04  106.160004  106.300003  104.699997  105.209999   
247   GOOG  2023-05-05  105.320000  106.440002  104.738998  106.214996   

      Adj Close    Volume  
0    154.414230  83322600  
1    151.688400  64120100  
2    150.639999  56007100  
3    151.009995  57450700  
4    153.850006  62199000  
..          ...       ...  
243  107.709999  20926300  
244  105.980003  20343100  
245  106.120003  17116300  
246  105.209999  19780600  
247  106.214996  20705300  

[248 rows x 8 columns]

In [5]:
dataset.head()

Ticker        Date        Open        High         Low       Close  \
0   AAPL  2023-02-07  150.639999  155.229996  150.639999  154.649994   
1   AAPL  2023-02-08  153.880005  154.580002  151.169998  151.919998   
2   AAPL  2023-02-09  153.779999  154.330002  150.419998  150.869995   
3   AAPL  2023-02-10  149.460007  151.339996  149.220001  151.009995   
4   AAPL  2023-02-13  150.949997  154.259995  150.919998  153.850006   

    Adj Close    Volume  
0  154.414230  83322600  
1  151.688400  64120100  
2  150.639999  56007100  
3  151.009995  57450700  
4  153.850006  62199000

In [6]:
dataset.tail()

Ticker        Date        Open        High         Low       Close  \
243   GOOG  2023-05-01  107.720001  108.680000  107.500000  107.709999   
244   GOOG  2023-05-02  107.660004  107.730003  104.500000  105.980003   
245   GOOG  2023-05-03  106.220001  108.129997  105.620003  106.120003   
246   GOOG  2023-05-04  106.160004  106.300003  104.699997  105.209999   
247   GOOG  2023-05-05  105.320000  106.440002  104.738998  106.214996   

      Adj Close    Volume  
243  107.709999  20926300  
244  105.980003  20343100  
245  106.120003  17116300  
246  105.209999  19780600  
247  106.214996  20705300

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
#drop rows with missing values
dataset.dropna(inplace=True)

In [21]:
dataset

Ticker        Date        Open        High         Low       Close  \
0     AAPL  2023-02-07  150.639999  155.229996  150.639999  154.649994   
1     AAPL  2023-02-08  153.880005  154.580002  151.169998  151.919998   
2     AAPL  2023-02-09  153.779999  154.330002  150.419998  150.869995   
3     AAPL  2023-02-10  149.460007  151.339996  149.220001  151.009995   
4     AAPL  2023-02-13  150.949997  154.259995  150.919998  153.850006   
..     ...         ...         ...         ...         ...         ...   
243   GOOG  2023-05-01  107.720001  108.680000  107.500000  107.709999   
244   GOOG  2023-05-02  107.660004  107.730003  104.500000  105.980003   
245   GOOG  2023-05-03  106.220001  108.129997  105.620003  106.120003   
246   GOOG  2023-05-04  106.160004  106.300003  104.699997  105.209999   
247   GOOG  2023-05-05  105.320000  106.440002  104.738998  106.214996   

      Adj Close    Volume  
0    154.414230  83322600  
1    151.688400  64120100  
2    150.639999  56007100  
3    151.009995  57450700  
4    153.850006  62199000  
..          ...       ...  
243  107.709999  20926300  
244  105.980003  20343100  
245  106.120003  17116300  
246  105.209999  19780600  
247  106.214996  20705300  

[248 rows x 8 columns]

In [23]:
x=dataset[['Open','High','Low','Close','Volume']]

In [24]:
x

Open        High         Low       Close    Volume
0    150.639999  155.229996  150.639999  154.649994  83322600
1    153.880005  154.580002  151.169998  151.919998  64120100
2    153.779999  154.330002  150.419998  150.869995  56007100
3    149.460007  151.339996  149.220001  151.009995  57450700
4    150.949997  154.259995  150.919998  153.850006  62199000
..          ...         ...         ...         ...       ...
243  107.720001  108.680000  107.500000  107.709999  20926300
244  107.660004  107.730003  104.500000  105.980003  20343100
245  106.220001  108.129997  105.620003  106.120003  17116300
246  106.160004  106.300003  104.699997  105.209999  19780600
247  105.320000  106.440002  104.738998  106.214996  20705300

[248 rows x 5 columns]

In [25]:
scaler=MinMaxScaler()

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
onehotencoder = OneHotEncoder()

In [36]:
x=onehotencoder.fit_transform(dataset.Volume.values.reshape(-1,1)).toarray()

In [37]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [40]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
y_train

array([[2.87000000e+02, 2.88480011e+02, 2.83690002e+02, 2.86140015e+02,
        2.09879000e+07],
       [1.53789993e+02, 1.56300003e+02, 1.53460007e+02, 1.53830002e+02,
        8.75580000e+07],
       [9.54199982e+01, 9.60899963e+01, 9.38440018e+01, 9.41699982e+01,
        2.41015000e+07],
       [1.46830002e+02, 1.47229996e+02, 1.45009995e+02, 1.45309998e+02,
        5.54790000e+07],
       [2.54479996e+02, 2.55490005e+02, 2.51589996e+02, 2.52669998e+02,
        2.83974000e+07],
       [1.53509995e+02, 1.56330002e+02, 1.53350006e+02, 1.53710007e+02,
        6.81679000e+07],
       [1.07389999e+02, 1.07970001e+02, 1.05599998e+02, 1.06949997e+02,
        1.97415000e+07],
       [3.25239990e+02, 3.30809998e+02, 3.24000000e+02, 3.29929993e+02,
        4.22190000e+06],
       [2.97899994e+02, 2.98790009e+02, 2.89000000e+02, 2.92760010e+02,
        5.75930000e+06],
       [3.40269989e+02, 3.43290009e+02, 3.35299988e+02, 3.38429993e+02,
        7.13150000e+06],
       [1.01059998e+02, 1.0258

In [43]:
y_test

array([[1.05320000e+02, 1.06440002e+02, 1.04738998e+02, 1.06214996e+02,
        2.07053000e+07],
       [3.40809998e+02, 3.42799988e+02, 3.30040009e+02, 3.31029999e+02,
        3.96540000e+06],
       [2.49070007e+02, 2.51490005e+02, 2.48729996e+02, 2.49419998e+02,
        2.24910000e+07],
       [3.04750000e+02, 3.16600006e+02, 3.01709991e+02, 3.10059998e+02,
        7.90370000e+06],
       [3.12079987e+02, 3.12510010e+02, 2.94880005e+02, 2.97779999e+02,
        7.44340000e+06],
       [2.55559998e+02, 2.56839996e+02, 2.50479996e+02, 2.54770004e+02,
        2.92191000e+07],
       [1.61630005e+02, 1.65800003e+02, 1.61419998e+02, 1.65559998e+02,
        6.84456000e+07],
       [3.26290009e+02, 3.32850006e+02, 3.25730011e+02, 3.32029999e+02,
        6.28730000e+06],
       [1.05739998e+02, 1.06160004e+02, 1.04739998e+02, 1.06059998e+02,
        2.52450000e+07],
       [1.00839996e+02, 1.03489998e+02, 1.00750000e+02, 1.02459999e+02,
        7.61403000e+07],
       [2.75790009e+02, 2.7614

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
sc_x=StandardScaler()

In [46]:
x_train=sc_x.fit_transform(x_train)

In [47]:
x_test=sc_x.transform(x_test)

In [48]:
x_train

array([[-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       ...,
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705]])

In [49]:
x_test

array([[-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       ...,
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705],
       [-0.07124705, -0.07124705, -0.07124705, ..., -0.07124705,
        -0.07124705, -0.07124705]])